### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by WMESN** [uatisdeproblem/esn-assembly#93]
When you create code it's under exclusive copyright by default. Without a license **nobody** else can copy, distribute, or modify your work without legal risks. Once your work has other contributers (each a copyright holder), **nobody** starts including you. Same goes for the egm app. For clarity towards ESN NOs a license should be included.

Popular licenses are MIT, GPL and Apache Licenses. Here's an overview of licenses: https://choosealicense.com/appendix/

**Comment by uatisdeproblem** [comment]
Hello there! Hard guess, you are Gabriel, right?

The repo is currently deliberately with no license since it was first private, and we still have to decide with the WPA how and if they want to make it available inside/outside the ESN scenario. 

I'll raise the topic and let you know in the next weeks. Thanks ;)

**Comment by WMESN** [comment]
What I mean is that you (not ESN) primarily hold the copyright to this work unless there is a specific agreement with ESN International. For instance, the TUMI App (an event management application) lacks a license, and it's unclear if there was any agreement between the creator and the organization. Now, if the creator establishes a company based on the product and Munich continues to use the software without charge, the company may request them to cease usage, citing ownership of the code.

**Comment by WMESN** [comment]
In summary, to ensure complete legal compliance, it's essential to either establish contracts with your volunteers or implement licenses before initiating projects. A license not only provides coverage for all future contributors but also represents a superior approach in terms of legal protection and clarity.

**Comment by uatisdeproblem** [comment]
I see your point, thank you for sharing Gabriel; I'll keep you posted in this thread. 🙂

**Comment by uatisdeproblem** [comment]
@WMESN FYI: after a discussion with the WPA, we agreed on a license, which is also compatible with other ESN projects' licenses.

Thank you for the heads-up!

**Comment by WMESN** [comment]
FIY even creative commons doesn't recommend using CC licenses for software (https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software). But I don't want to be annoying and nitpicky 🙏 . I will suggest in the next ITcom call a license we can consider for future projects.
